from __future__ import annotations

import json
import re
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
TASK_ID = "1d429cf4b8bb"
BATCH_ID = "8760319e46bf"
TOPIC_TITLE = "女子高铁叫嚣全家体制内 官方通报"


def _run(command: list[str]) -> str:
    completed = subprocess.run(command, cwd=ROOT, text=True, encoding="utf-8", errors="replace", capture_output=True)
    return (
        f"COMMAND={' '.join(command)}\n"
        f"EXIT_CODE={completed.returncode}\n"
        f"STDOUT:\n{completed.stdout}\n"
        f"STDERR:\n{completed.stderr}\n"
    )


def _copy(src: str, dst_root: Path) -> None:
    source = ROOT / src
    if not source.exists():
        return
    dest = dst_root / src
    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, dest)


def _redact_settings(out: Path) -> None:
    source = ROOT / "config" / "settings.json"
    if not source.exists():
        out.write_text("MISSING config/settings.json\n", encoding="utf-8")
        return
    data = json.loads(source.read_text(encoding="utf-8"))

    def redact(value):
        if isinstance(value, dict):
            return {k: ("***REDACTED***" if re.search(r"api[_-]?key|secret|token", k, re.I) and v else redact(v)) for k, v in value.items()}
        if isinstance(value, list):
            return [redact(item) for item in value]
        return value

    out.write_text(json.dumps(redact(data), ensure_ascii=False, indent=2), encoding="utf-8")


def main() -> int:
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    pkg_root = ROOT / "release" / f"p1_quality_research_review_{stamp}"
    source_dir = pkg_root / "source"
    evidence_dir = pkg_root / "evidence"
    source_dir.mkdir(parents=True, exist_ok=True)
    evidence_dir.mkdir(parents=True, exist_ok=True)

    source_files = [
        "generation/content_quality.py",
        "generation/article_generator.py",
        "generation/angle_planner.py",
        "generation/topic_classifier.py",
        "research/service.py",
        "research/discovery.py",
        "research/extractor.py",
        "export/layout_pipeline.py",
        "start_backend_dev.py",
        "scripts/audit_missing_topic_ids.py",
        "scripts/p1_fresh_hotspot_repro.py",
        "scripts/package_p1_review_evidence.py",
        "tests/test_p1_article_quality_research_fix.py",
        "tests/test_p1_hf4_1_r1_2_data_integrity_runtime.py",
    ]
    for file in source_files:
        _copy(file, source_dir)

    evidence_files = [
        "data/logs/api.log",
        "data/logs/dev_start_stdout.log",
        "data/logs/dev_start_stderr.log",
        "data/logs/p1_fresh_hotspot_direct_repro_transcript.json",
        f"data/data/tasks/{TASK_ID}/article.md",
        f"data/data/tasks/{TASK_ID}/article.json",
    ]
    for file in evidence_files:
        _copy(file, evidence_dir)
    if not (ROOT / "data" / "logs" / "error.log").exists():
        (evidence_dir / "error.log.MISSING.txt").write_text("MISSING: no error.log generated in this clean dev run.\n", encoding="utf-8")
    else:
        _copy("data/logs/error.log", evidence_dir)
    if not (ROOT / "data" / "logs" / "startup.log").exists():
        (evidence_dir / "startup.log.MISSING.txt").write_text(
            "MISSING: dev startup uses dev_start_stdout.log/dev_start_stderr.log; startup.log is not generated by start_backend_dev.py.\n",
            encoding="utf-8",
        )
    else:
        _copy("data/logs/startup.log", evidence_dir)

    py = sys.executable
    (evidence_dir / "db_missing_topic_id_audit.txt").write_text(_run([py, "scripts/audit_missing_topic_ids.py"]), encoding="utf-8")
    (evidence_dir / "netstat_8505_8506.txt").write_text(_run(["cmd", "/c", 'netstat -ano | findstr "8506 8505"']), encoding="utf-8")
    (evidence_dir / "tasklist_python.txt").write_text(_run(["cmd", "/c", "tasklist | findstr python"]), encoding="utf-8")
    (evidence_dir / "pytest_p1_quality.txt").write_text(
        _run(
            [
                py,
                "-m",
                "pytest",
                "-q",
                "tests/test_p1_article_quality_research_fix.py",
                "tests/test_p1_hf4_1_r1_2_data_integrity_runtime.py",
                "tests/test_p1_hf4_1_r1_2_article_quality_delivery.py",
                "tests/test_p1_hf4_1_r1_2_export_gate_consistency.py",
                "--basetemp=.pytest_tmp_codex_p1_quality",
            ]
        ),
        encoding="utf-8",
    )
    (evidence_dir / "compileall.txt").write_text(_run([py, "-m", "compileall", "generation", "export", "research", "scripts", "-q"]), encoding="utf-8")
    (evidence_dir / "git_diff_stat.txt").write_text(_run(["git", "diff", "--stat"]), encoding="utf-8")
    (evidence_dir / "git_diff.patch").write_text(_run(["git", "diff", "--", ".", ":(exclude)release", ":(exclude)runtime"]), encoding="utf-8")
    (evidence_dir / "git_status_short.txt").write_text(_run(["git", "status", "--short"]), encoding="utf-8")
    _redact_settings(evidence_dir / "settings.redacted.json")

    article_md = ROOT / "data" / "data" / "tasks" / TASK_ID / "article.md"
    article_text = article_md.read_text(encoding="utf-8", errors="replace") if article_md.exists() else ""
    article_scan = {
        "visible_chinese_chars": len(re.findall(r"[\u4e00-\u9fff]", article_text)),
        "bad_patterns": [
            item
            for item in [
                "钩子开头",
                "30秒速览",
                "单点深挖",
                "单点深化",
                "观点判断",
                "结尾互动",
                "，、",
                "、，",
                "，，",
                "；，",
                "，；",
                "资料来源",
                "AI辅助",
                "AI声明",
                "免责声明",
            ]
            if item in article_text
        ],
        "headings": re.findall(r"^##\s+(.+)$", article_text, re.M),
    }
    readme = f"""P1 quality/research review package
Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
Workspace: {ROOT}

Final real run:
- batch_id: {BATCH_ID}
- task_id: {TASK_ID}
- topic: {TOPIC_TITLE}
- elapsed_seconds: 33.51
- article scan: {json.dumps(article_scan, ensure_ascii=False)}
- text model HTTP: 200 OK in evidence/data/logs/api.log

Code fixes included:
- research/service.py: Bing fallback URL fixed to /search?q=
- generation/article_generator.py: fixed public H2 structure, paragraph splitting regex, delivery polish and length fill
- generation/content_quality.py: hard-fact cleanup no longer strips sentence-ending punctuation
- export/layout_pipeline.py: final visible content_markdown is rebuilt from structured article and length-filled before save/export
- start_backend_dev.py: PYTHONUTF8/PYTHONIOENCODING set for readable logs
- scripts/audit_missing_topic_ids.py: real DB audit script, no heredoc dependency

DB audit:
- See evidence/db_missing_topic_id_audit.txt. Expected: EXIT_CODE=0 and BAD_TOPIC_SNAPSHOTS=[].

Note:
- The final clean api.log uses cached research for the same hot topic, so it mainly shows batch submit and the final text model POST.
- Earlier fresh run after source fix showed Bing URLs as https://www.bing.com/search?q=... and cn.bing.com/search?q=...; the source fix is included in research/service.py and git_diff.patch.
"""
    (pkg_root / "README_FOR_CLAUDE.txt").write_text(readme, encoding="utf-8")

    archive_base = str(pkg_root)
    zip_path = shutil.make_archive(archive_base, "zip", pkg_root)
    print(zip_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
